// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/auth-ui/Dashboard.tsx": () => import("../components/mockups/auth-ui/Dashboard.tsx"),
  "./components/mockups/auth-ui/Login.tsx": () => import("../components/mockups/auth-ui/Login.tsx")
};
